### ISSUE TITLE
reference error when using attack-scripts as submodule

### ISSUE THREAD

**Issue by Git-Minty** [mitre-attack/attack-scripts#64]
Line 10 in attack-scripts/layers/exporters/to_svg.py:
`from layers.core import Layer as topLayer # alternative import for typechecking`

throws the error that it cannot find the layer module.  I am running attack-scripts as a submodule in a project (not sure if that changes anything).  Removing that line fixes the issue on my end.

**Comment by isaisabel** [comment]
Hi @rdminter,

We recently migrated the layer library over to our new [mitreattack-python](https://github.com/mitre-attack/mitreattack-python) pip module. This should help avoid weird import errors since the importing is a lot more standardized now that it's a pip module.

I'm going to close this issue under the presumption that it is irrelevant with the new importing on [mitreattack-python](https://github.com/mitre-attack/mitreattack-python), but if it's still a problem over there please feel free to open a new issue [on the issue tracker of that module](https://github.com/mitre-attack/mitreattack-python/issues).
